### ISSUE TITLE
version3.2 - upgrade_3102 : Value already exists in the database

### ISSUE THREAD

**Issue by tapashdatta** [mattwire/uk.co.compucorp.civicrm.giftaid#1]
Receiving during upgrade..

```
$CRM_Queue_Page_AJAX_runNext_error = CiviCRM_API3_Exception: "Value already exists in the database" #0 /home/webadmin/public_html/cmm/sites/default/files/civicrm/ext/uk.co.compucorp.civicrm.giftaid/CRM/Civigiftaid/Upgrader.php(234): civicrm_api3("OptionValue", "create", (Array:5)) #1 /home/webadmin/public_html/cmm/sites/default/files/civicrm/ext/uk.co.compucorp.civicrm.giftaid/CRM/Civigiftaid/Upgrader/Base.php(72): CRM_Civigiftaid_Upgrader->upgrade_3102() #2 /home/webadmin/public_html/cmm/sites/all/modules/civicrm/CRM/Queue/Task.php(88): CRM_Civigiftaid_Upgrader_Base::_queueAdapter(Object(CRM_Queue_TaskContext), "upgrade_3102") #3 /home/webadmin/public_html/cmm/sites/all/modules/civicrm/CRM/Queue/Runner.php(217): CRM_Queue_Task->run(Object(CRM_Queue_TaskContext)) #4 /home/webadmin/public_html/cmm/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(52): CRM_Queue_Runner->runNext(TRUE) #5 /home/webadmin/public_html/cmm/sites/all/modules/civicrm/CRM/Queue/ErrorPolicy.php(106): CRM_Queue_Page_AJAX::{closure}() #6 /home/webadmin/public_html/cmm/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(54): CRM_Queue_ErrorPolicy->call(Object(Closure)) #7 /home/webadmin/public_html/cmm/sites/all/modules/civicrm/CRM/Core/Invoke.php(277): CRM_Queue_Page_AJAX::runNext() #8 /home/webadmin/public_html/cmm/sites/all/modules/civicrm/CRM/Core/Invoke.php(85): CRM_Core_Invoke::runItem((Array:13)) #9 /home/webadmin/public_html/cmm/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:4)) #10 /home/webadmin/public_html/cmm/sites/all/modules/civicrm/drupal/civicrm.module(444): CRM_Core_Invoke::invoke((Array:4)) #11 /home/webadmin/public_html/cmm/includes/menu.inc(527): civicrm_invoke("queue", "ajax", "runNext") #12 /home/webadmin/public_html/cmm/index.php(21): menu_execute_active_handler() #13 {main}
--



```

**Comment by mattwire** [comment]
@tapashdatta Does this still occur?
